

services:
  broker:
    build: ./broker
    container_name: broker
    volumes:
      - ./broker/broker.py:/app/main.py
    ports:
      - "5555:5555"
      - "5556:5556"

  servidor1:
    build: ./server
    container_name: servidor1
    volumes:
      - ./server/server.py:/app/main.py
    depends_on:
      - broker
      - proxy_pubsub 

  servidor2:
    build: ./server-java
    container_name: servidor2
    depends_on:
      - broker

  cliente1:
    build: ./client
    container_name: cliente1
    volumes:
      - ./client/client.py:/app/main.py
    depends_on:
      - broker

  cliente2:
    build: ./client-java
    container_name: cliente2
    depends_on:
      - broker

  proxy_pubsub:
    build: ./proxy_pubsub
    container_name: proxy_pubsub
    volumes:
      - ./proxy_pubsub/proxy_pubsub.py:/app/main.py
    ports:
      - "5557:5557"
      - "5558:5558" 

  bot:
    build: ./bot
    container_name: bot
    volumes:
      - ./bot/bot.py:/app/main.py
    depends_on:
      - broker
      - proxy_pubsub   

  
  coordenador:
    build: ./coordenador
    container_name: coordenador
    ports:
      - "5560:5560"